### ISSUE TITLE
error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by debalance** [rwthmoodle/Sync-my-L2P#12]
**Describe the bug**
Unable to launch Sync-my-L2P on Debian Bullseye and Debian Sid

**To Reproduce**
1. Download the AppImage
2. `chmod a+x SyncMyL2P-2.4.2-linux.AppImage`
3. `./SyncMyL2P-2.4.2-linux.AppImage`
4. See error:
```
./SyncMyL2P-2.4.2-linux.AppImage: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory
```

**Expected behavior**
The AppImage should contain all required libraries so the application can start on any and all Linux distros.

**Desktop (please complete the following information):**
 - OS: Debian GNU|Linux
 - Version: 11
 
 **Context**
 Only the following Versions of libicui18n.so are available on Debian 11:
```
~$ apt-file search libicui18n.so
libicu63: /usr/lib/x86_64-linux-gnu/libicui18n.so.63
libicu63: /usr/lib/x86_64-linux-gnu/libicui18n.so.63.2
libicu67: /usr/lib/x86_64-linux-gnu/libicui18n.so.67
libicu67: /usr/lib/x86_64-linux-gnu/libicui18n.so.67.1
libicu68: /usr/lib/x86_64-linux-gnu/libicui18n.so.68
libicu68: /usr/lib/x86_64-linux-gnu/libicui18n.so.68.2
```

**Comment by t-schroeder** [comment]
Thanks for reporting this. I also noticed that version 56 of libicui18n (and two other libs) wasn't available on Ubuntu 18.04 which we build on. Qt 5.15 links against these at build time. So I compiled them by hand, checked them in to this repository at [./linux/libs](https://github.com/rwthmoodle/Sync-my-L2P/tree/master/linux/lib) and they are also in the AppImage under ./lib but seems they are just not found when running the AppImage. They probably need to go into ./usr/lib or ./squashfs-root/usr/lib where all the other libs are. I'll try to reproduce and fix this in the coming week.

Meanwhile you can download the libs from [./linux/libs](https://github.com/rwthmoodle/Sync-my-L2P/tree/master/linux/lib) or build them yourself as described in [./linux/lib/Readme.md](https://github.com/rwthmoodle/Sync-my-L2P/blob/master/linux/lib/Readme.md).

**Comment by debalance** [comment]
Thank you @t-schroeder, after placing those precompiled libs in `/usr/local/lib/` and calling `ldconfig`
Sync-my-L2P launches successfully and works as expected. :+1: 
It is an ugly workaround but quite okay if it's only temporary.

**Comment by t-schroeder** [comment]
Should be fixed now. I recreated the 2.4.2 release with the new AppImage.
