### ISSUE TITLE
Long Path Error on windows

### ISSUE THREAD

**Issue by Tastaturtaste** [rwthmoodle/Sync-my-L2P#15]
When syncing files with moodle on windows an error occurs because the path is longer than 260 characters. Presumably this restriction was added because of windows maximum path length limitation when using unprefixed paths.
Since both the windows api and qt support long path names with up to 32767 characters this seems like a pretty arbitrary restriction which hopefully can be lifted by appending _\\?\_ to the download path according to the documentation of windows max path length limitations. 
This would prevent a very common error nearly everyone using windows currently encounters. 
As I understand it the required change would be to delete the current manual check for the path length on windows and maybe prepend the above mentioned prefix to the download path. 

[Source for windows max path length limitations](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)
[Source for qt support for long path names](https://forum.qt.io/topic/84796/does-qdir-impose-a-maximum-path-limit-on-windows/2)

**Comment by Tastaturtaste** [comment]
This issue was also reported on the old repository:
https://github.com/RobertKrajewski/Sync-my-L2P/issues/162

A different fix was proposed, requiring checking for a registry key which enables long path names by default without the prefix. This is available only on windows >= 10 update 1607. 
My proposed fix would probably work for older systems as well, but checking the flag and enabling long paths only for modern systems would probably be good enough for the majority of students.

**Comment by t-schroeder** [comment]
This should be fixed with the 2.4.5 release.

**Comment by Tastaturtaste** [comment]
It is, thank you very much!
