### ISSUE TITLE
StatusCode 104 when getting enrolled courses

### ISSUE THREAD

**Issue by Mayiaz** [rwthmoodle/Sync-my-L2P#30]
**Describe the bug**
Whenever the tool starts reading the enrolled courses from Moodle I get an error with a status code 104 and status info Semester 2312 not available.

It happens after the api call https://moped.ecampus.rwth-aachen.de/proxy/api/v2/eLearning/Moodle/getmyenrolledcourses?token=[MyToken]&semesterOffset=0
I tryed to open the link from a browser it works without the semesterOffset param or with the semesterOffset set to wsXX but not to a number (it's 0 in the original requist). I'm not sure if that is because of the new update for Moodle, the tool or my Moodle account 

**To Reproduce**
1. Log in
2. Go to 'Filebrowser'
3. Click on 'Update'
4. Go to 'Log'
5. See error

**Screenshots**
![image](https://github.com/rwthmoodle/Sync-my-L2P/assets/10568909/c2ea4277-7be1-4d06-ba11-24639c21daac)

**Desktop:**
 - OS: Windows 11
 - Version v2.5.1a

**Comment by t-schroeder** [comment]
Thanks for the issue report. We've fixed this in moped.ecampus.rwth-aachen.de
