### ISSUE TITLE
Sync-my-L2P not responding after launch and no UI is displayed

### ISSUE THREAD

**Issue by deichcode** [rwthmoodle/Sync-my-L2P#9]
**Describe the bug**
When launching the application on macOS Big Sur no UI is showing up and the process becomes not responding. In this state it consumes nearly a complete logical CPU core.

**To Reproduce**
1. Download Sync-my-L2P
2. Mount .dmg file
3. Copy Sync-my-L2P to Application folder
4. Open Sync-my-L2P by right click -> Open
5. Confirm launch of App
6. No UI is showing up, Process is shown as "Not Responding" in Activity Manager, Process takes about 80-90% of a logical CPU core

**Expected behavior**
Would expect, that UI of the application shows up

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.2.3

**Additional context**
The previous version from Robter Krajewski's repository (v2.4.1) has a normal launching behavior. Links to working Version: https://github.com/RobertKrajewski/Sync-my-L2P/releases/tag/v2.4.1

**Comment by t-schroeder** [comment]
Thanks for the report. I've fixed this and re-created the 2.4.2 release with a working macOS version.

**Comment by t-schroeder** [comment]
This problem is fixed if we use Qt 5.15 but then building the linux appimage fails. Working on it.

**Comment by t-schroeder** [comment]
I did a new v2.4.2 release with the macOS version really working this time.
